services:
  cleaner:            
    build: .           
    image: hotel-bookings-cleaner:3.0-k8s  
    volumes:
      - .:/app        
    stdin_open: true   
    tty: true          
    depends_on:
      - postgres_db

  postgres_db:
   image: postgres:18
   restart: always
   shm_size: 128mb
   volumes:
      - ./db-data/:/var/lib/postgresql/
   ports:
      - "5462:5432" 
   environment:
     POSTGRES_PASSWORD: use_env_in_practise_;)