services:
  cleaner:             # This is just a name you give the service
    build: .           # <--- THIS replaces 'docker build .'
    image: hotel-bookings-cleaner:3.0-k8s  # Optional: names the image
    volumes:
      - .:/app         # Replaces '-v $(pwd):/app'
    stdin_open: true   # Replaces '-i' (Interactive)
    tty: true          # Replaces '-t' (Terminal)
    depends_on:
      - postgres_db

  postgres_db:
   image: postgres:18
   restart: always
   shm_size: 128mb
   volumes:
      - ./db-data/:/var/lib/postgresql/
   ports:
      - "5462:5432" 
   environment:
     POSTGRES_PASSWORD: use_env_in_practise_;)